HubSpot/calling-extensions-sdk

README.md
demo/index.html
demo/index.js

Removed callData event from demo

---

.npmrc
.travis.yml
README.md
demo/index.html
demo/package.json
demo/webpack.config.js

Infrastructure Improvements
1) Added .travis.yml
2) Simplified running the demo; no longer need to create certs or install http-server

Infrastructure improvements

---

README.md

https://github.com/HubSpot/calling-extensions-sdk/issues/31

Adding portalId to onDialNumber

---

README.md

Developer Support team does not monitor the forums.  It is a community led environment

ammend dev support from community statement

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Configures the repo for collaboration and issue support.
Inspired by https://github.com/HubSpot/cms-theme-boilerplate

Configure repo for GitHub

---

README.md

Improve the setup instructions by:
-  rearranging the getting started steps
- creating new sections
- paraphrasing explanations
- removing the deprecated comments since it has now been a while
https://issues.hubspotcentral.com/browse/CALL-3047
Tested locally in IDE.

Improve the setup docs

---

demo-v1/src/components/screens/KeypadScreen.tsx
demo-v1/test/spec/components/screens/KeypadScreen-test.tsx

JIRA Ticket: CALL-2987
Allow characters within the keypad: `0-9*#`

Add minimal phone number validation to keypad

---

demo-v1/src/components/App.tsx
demo-v1/src/components/screens/CallEndedScreen.tsx
demo-v1/src/components/screens/CallingScreen.tsx
demo-v1/src/components/screens/DialingScreen.tsx
demo-v1/src/components/screens/KeypadScreen.tsx
demo-v1/src/hooks/useCti.ts
demo-v1/src/types/ScreenTypes.ts
demo-v1/test/render.tsx
demo-v1/test/spec/components/App-test.tsx
demo-v1/test/spec/components/screens/CallEndedScreen-test.tsx
demo-v1/test/spec/components/screens/CallingScreen-test.tsx
demo-v1/test/spec/components/screens/DialingScreen-test.tsx
demo-v1/test/spec/components/screens/KeypadScreen-test.tsx
demo-v1/test/spec/components/screens/LoginScreen-test.tsx

JIRA Tickets: CALL-3106, CALL-2984
Backfill unit tests for screens and CTI eventhandlers.
Update `cti.callCompleted` event to take in `engagementProperties`.

Backfill unit tests

---

.github/PULL_REQUEST_TEMPLATE.md

Add BRAVE checklist to PR template

---

demos/demo-minimal-js/index.js
demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
demos/demo-react-ts/src/hooks/useCti.ts

Jira Ticket: CALL-3289
- Update demos to use latest sdk package version
- Update imports to use the sdk package by default, with alternative import commented out for development until we have an npm link script.
| Rollout/Rollback Plan?         | Create a revert PR then create a new patch version.
| Automated test …

Update demos to use latest sdk package version

---

README.md
demos/demo-minimal-js/README.md
demos/demo-minimal-js/package.json
demos/demo-react-ts/README.md
demos/demo-react-ts/package.json
demos/package.json

Jira Ticket: CALL-3402
| Adds Documentation?      | :white_check_mark:

Demo readme

---

demo/package-lock.json
demo/package.json
package-lock.json
package.json
src/CallingExtensions.js
src/IFrameManager.js
src/packageInfo.js
test/spec/CallingExtensions-test.js

Jira Ticket: CALL-3266
- Add unit tests for callCompleted and outgoingCall
- Update initialized payload to include `sdkVersion`
- Publish only whitelisted files to npm
| Rollout/Rollback Plan?         | Publish and update dependency to `0.0.13-alpha.0`
| Automated test coverage?       | Unit tests
| Verified that changes work?    | :white_check_mark: …

Update and fix SDK tests

---

demo/package-lock.json
demo/package.json
demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json
src/CallingExtensions.js
src/IFrameManager.js
src/packageInfo.js
test/spec/CallingExtensions-test.js

Jira Ticket: CALL-2989
Publish alpha version.

Publish new alpha version

---

README.md
demos/package.json

Jira Ticket: CALL-3438
Update demo widget names and simplify README.
| Adds Documentation?      | ✅ 

Rename demo widgets

---

.github/workflows/deploy.yml
.github/workflows/preview.yml
demos/demo-minimal-js/package.json
demos/demo-react-ts/package.json
demos/demo-react-ts/src/components/Components.tsx
demos/demo-react-ts/src/components/screens/LoginScreen.tsx
demos/demo-react-ts/src/visitor-ui-component-library/input/VizExInput.js
demos/demo-react-ts/webpack.config.js
demos/package.json
src/IFrameManager.js

Jira Ticket: CALL-3440, CALL-3469
Fixes build warnings and provide more details for iFrame is not initialized message.
| Verified that changes work?    | :white_check_mark:

Fix demo app build warnings and iFrame uninitialized message

---

.github/CODEOWNERS

Update team name

---

README.md
demos/demo-minimal-js/index.html
demos/demo-minimal-js/index.js

Jira Ticket: CALL-3156
Enforce order of events in demo-minimal-js by disabling the buttons. Also adds a timer and sends callStartTime to HubSpot.
To follow up with styling changes to demo-minimal-js.
| Patch: Bug Fix?          | :white_check_mark:
| Expect Dependencies to Fail? …

Enforce order of events in demo minimal js

---

README.md

Jira Ticket: CALL-3684
| Adds Documentation?      |:white_check_mark:
| Rollout/Rollback Plan?         | Merge PR / Revert PR

Use new local value to install the demo widget

---

.github/workflows/deploy.yml
.github/workflows/preview.yml
demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json

Jira Ticket: CALL-3749
| Patch: Bug Fix?          | :white_check_mark:

Enable github actions

---

.github/workflows/preview.yml
demos/demo-minimal-js/README.md
demos/demo-react-ts/README.md

Update demo documentation

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

Jira Ticket: CALL-3789
Testing out separate publish PRs

Publish v0.1.3

---

package-lock.json
package.json

Jira Ticket: CALL-3877
GH Issue: https://github.com/HubSpot/calling-extensions-sdk/issues/131 
Include javascript files to support the `module` field for bundlers like Rollup or Webpack 2 to import these files directly.
| Verified that changes work?    | ✅ Tested with alpha …

Support the module field in package.json

---

demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx

Jira Ticket: CALL-3262
We will use the `engagementProperties` field to update HubSpot owned engagements in the future. In the meantime, we should inform users that this is not yet in place.
| Adds Documentation?      | yes

Add JSDoc comments for engagement properties

---

package-lock.json
package.json
src/CallingExtensions.js
src/Constants.js
src/IFrameManager.js
src/packageInfo.js
test/spec/CallingExtensions-test.js
test/spec/IFrameManager-test.js

Jira Ticket: CALL-3765
- Optimize creation of type constants
- Consolidate getVersion() method into VERSION constant
- Fix `version` prop in SYNC_ACK event
- Remove `sdkVersion` prop from INITIALIZED event to avoid duplication
| Automated test coverage?       | Unit tests
| Verified …

Refactor type and version constants

---

demos/demo-minimal-js/package-lock.json
demos/demo-react-ts/package-lock.json
package-lock.json
package.json

Publish 0.1.6

---

demos/demo-minimal-js/index.html
demos/demo-minimal-js/index.js
demos/demo-react-ts/src/components/screens/KeypadScreen.tsx
demos/demo-react-ts/test/spec/components/screens/KeypadScreen-test.tsx

Jira Ticket: CALL-3763
Add `incoming call started` button to demo minimal js.

Create incoming call method to test inbound calling

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

Publish 0.1.7

---

demos/demo-minimal-js/index.html
demos/demo-minimal-js/index.js

Reverts HubSpot/calling-extensions-sdk#145

Revert "Initialize demo widget when ready event is received from HubSpot"

---

demos/demo-minimal-js/index.html
demos/demo-minimal-js/index.js

Jira Ticket: CALL-3809
Show initialized UI changes when `ready` event is received by disabling and enabling buttons.

Extensions inbound lifecycle

---

README.md
demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

Jira Ticket: CALL-5011
| Adds Documentation?      | yes

Update docs with hs owned engagements event handlers

---

README.md
demos/demo-react-ts/src/components/App.tsx
demos/demo-react-ts/src/hooks/useCti.ts

Navigate to record page in the react demo app

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json

Jira Ticket: [CALL-5597](https://issues.hubspotcentral.com/browse/CALL-5597)

Publish new version: v0.2.1

---

package.json
webpack.config.js

Jira Ticket: CALLING-11266
We are using the development mode to build the main.js bundle of the npm package. This causes issues when installing the package via a CDN, and lacks optimization.
| Patch: Bug Fix?          | :white_check_mark:
| Backwards Compatible?          | :white_check_mark:
| Verified that changes work?    | :white_check_mark:
| …

Use production mode to build the SDK bundle.

---

README.md
demos/demo-minimal-js/index.html
demos/demo-minimal-js/index.js
demos/demo-react-ts/src/components/App.tsx
demos/demo-react-ts/src/components/AvailabilityDropdown.tsx
demos/demo-react-ts/src/components/Components.tsx
demos/demo-react-ts/src/hooks/useCti.ts
demos/demo-react-ts/test/spec/components/App-test.tsx

Jira Ticket: CALL-5990
| Backwards Compatible?          | ✅ 
| Verified that changes work?    | ✅ 

Add beta badge to incoming call, availability toggles

---

demos/demo-minimal-js/index.js

Jira Ticket: CALL-6383
Introduce method for testing the new event.
| Minor: New Feature?      |:white_check_mark:

Use publishToChannel in demo minimal JS

---

demos/demo-react-ts/src/components/screens/CallingScreen.tsx
demos/demo-react-ts/src/components/screens/DialingScreen.tsx
demos/demo-react-ts/test/spec/components/screens/CallingScreen-test.tsx
demos/demo-react-ts/test/spec/components/screens/IncomingScreen-test.tsx

Fix callStatus issue in the demo widget

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

Publish 0.6.1

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json
src/CallingExtensions.js

Jira Ticket: CALL-6911
| Backwards Compatible?          | ✅ 

CALL-6911: Pass in payload for onCallAnswered handler

---

demos/demo-react-ts/src/components/AvailabilityDropdown.tsx
demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx
demos/demo-react-ts/src/components/screens/CallingScreen.tsx
demos/demo-react-ts/src/components/screens/DialingScreen.tsx
demos/demo-react-ts/src/components/screens/IncomingScreen.tsx
demos/demo-react-ts/src/components/screens/KeypadScreen.tsx
demos/demo-react-ts/src/components/screens/LoginScreen.tsx
demos/demo-react-ts/src/constants/buttonIds.ts
demos/demo-react-ts/test/spec/components/screens/KeypadScreen-test.tsx
demos/demo-react-ts/test/spec/run-test.ts

Jira Ticket: CALL-6739
Add test ids for popup ATs.
Configure testIdAttribute in React Testing Library to `data-test-id` since it is our [internal default](https://product.hubteam.com/docs/frontend-testing/static/acceptance-test/fundamentals.html#accessing-elements).
| Verified that …

Add test ids for popup ATs

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

Jira Ticket: CALL-6780
| Minor: New Feature?      | ✅ 

Publish 0.7.0

---

demos/demo-react-ts/src/hooks/useCti.ts

Set isLoggedIn and isAvailable to false on INITIALIZED

---

demos/demo-minimal-js/index.js
demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json

Jira Ticket: CALLING-12288
Bump version for changes in https://github.com/HubSpot/calling-extensions-sdk/pull/234.
Redirect to a new url domain.

Bump npm version for demo minimal js

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

GitHub: [732](https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/732)

Publish 0.8.0

---

README.md

[GitHub issue 876](https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/876)
| Adds Documentation?      |:white_check_mark: …

Direct users to "get help with HubSpot" doc

---

demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx
demos/demo-react-ts/src/components/screens/CallingScreen.tsx
demos/demo-react-ts/src/types/ScreenTypes.ts
demos/demo-react-ts/test/spec/components/screens/CallEndedScreen-test.tsx
demos/demo-react-ts/test/spec/components/screens/CallingScreen-test.tsx

Update event handlers from iframeLocation change

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
demos/demo-react-ts/package-lock.json
demos/demo-react-ts/package.json
package-lock.json
package.json

Publish v0.8.1

---

demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx
demos/demo-react-ts/src/constants/buttonIds.ts
demos/demo-react-ts/src/hooks/useCti.ts
demos/demo-react-ts/test/spec/components/screens/CallEndedScreen-test.tsx
package-lock.json
package.json

GH Ticket: https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/879
This PR aims at triggering publishToChannel event on call completed.
| Automated test coverage?       |  ✅ 

Call PublishToChannel on call completed

---

demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx
package-lock.json
package.json

Rename button for Publish to Channel

---

demos/demo-react-ts/src/components/screens/KeypadScreen.tsx

Fix failing popup tests as click to dial does not allow user to start a call.
| Patch: Bug Fix?          | X

Validate dialNumber in useEffect hook

---

demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json
package-lock.json
package.json

Publish 0.9.1-alpha.0

---

demos/demo-minimal-js/index.html
demos/demo-minimal-js/index.js
demos/demo-minimal-js/package-lock.json
demos/demo-minimal-js/package.json

Update demo-minimal-js to load SDK from CDN

---

demos/demo-react-ts/src/hooks/useCti.ts

Send usesCallingWindow prop to react demo widget.
| Patch: Bug Fix?          | x

Send usesCallingWindow to react demo widget

---

demos/demo-react-ts/src/index.html

Update react cdn src
