HubSpot/calling-extensions-sdk

- README.md
- src/CallingExtensions.js
- src/Constants.js
Add clarifications on how to develop with the SDK, with improved event-handling sequences for  `SYNC` and `INITIALIZED`.
When placing a call, an event `SET_CALL_STATE` is emitted which will cause an error to be thrown since no event handler is listening for it.
Add `SET_CALL_STATE` to prevent throwing errors on new call
> Prevent error on SET_CALL_STATE, update README

- README.md
- demo/index.html
- demo/index.js
- src/CallingExtensions.js
- src/Constants.js
The call completed event serves two goals -
1) Insert the call engagement into the record's timeline
2) Hide the communicator w/o user having to do so.
In addition, updated the documentation.
> Added support for call competed event.

- README.md
- demo/index.js
- src/CallingExtensions.js
- src/Constants.js
The call engagements should have context related associations.  For example, the engagement for a call made to a contact from a deal page should have tha deal associated.  Precalculating these associations requires API calls; adding time to the dial number event.  Getting the engagementId from the widget is also not practicle as widget may be creatig the engagements as a batch process given that creating engagement is not critical to connecting a call.
The change allows the widget to receive an engagement created by HubSpot - the engagement will be created on receiving the outgoing_call event and send it back to the widget as part of onEngagementCreated event.  The widget backend can update this engagement with call details instread of creating a new engagement.
> Added an event handler for receiving a HubSpot created engagement,

- README.md
Adding new optional parameter `hideWidget` to callCompleted. This will give providers the ability to optionally keep the widget open after save.
> Adding documentation for callCompleted hideWidget option

- README.md
In the readme there’s reference and links to API keys that are incorrect. So they need to explicitly link to Developer API keys. Especially since API keys are now sunset.
> Update developer API key link and wording.

- README.md
Update README to mark `LocalSettings:Sales:CallingExtensions` as deprecated as it has been replaced by `LocalSettings:Calling:CallingExtensions`.
> Mark LocalSettings:Sales:CallingExtensions as deprecated 

- .github/workflows/preview.yml
- .gitignore
- demo-v1/dist/index.html
- demo-v1/package.json
- demo-v1/src/components/App.tsx
- demo-v1/src/index.html
- demo-v1/webpack.config.js
- demo/index.html
- demo/package.json
- demo/webpack.config.js
- package.json
- src/index.html
Jira Ticket: CALL-3006
Deployed on GH Pages: https://github.hubspot.com/calling-extensions-sdk
Build folder structure
```
build
- demo.html
- demo.bundle.js
- demo-v1.html
- demo-v1.bundle.js
- index.html
```
To build files: `npm run build:demos`
To deploy to [gh-pages](https://github.com/HubSpot/calling-extensions-sdk/tree/gh-pages): `npm run deploy`
> Deploy demo apps to GH pages

- .github/workflows/preview.yml
- demo-v1/src/components/Alert.tsx
- demo-v1/src/components/App.tsx
- demo-v1/src/components/Components.tsx
- demo-v1/test/spec/components/App-test.tsx
- demo-v1/test/spec/components/screens/KeypadScreen-test.tsx
- demo-v1/test/spec/components/screens/LoginScreen-test.tsx
JIRA Ticket: CALL-3097
- Add developer console alert to demo app with a confirm button to close the alert.
- Update PR previews to include all branches containing the `demo` keyword, not just `project-demo-v1`
> Demo console banner

- demo-v1/src/components/App.tsx
- demo-v1/src/hooks/useCti.ts
- demo-v1/src/hooks/useTimer.ts
- demo-v1/src/types/EngagementStatuses.ts
JIRA Ticket: CALL-2984
Send notes and call duration data to CallingExtensions SDK in `callCompleted`.
> Send additional call engagement properties in call completed data

- demo-v1/src/components/screens/KeypadScreen.tsx
- demo-v1/src/hooks/useCti.ts
- demo-v1/test/spec/components/screens/KeypadScreen-test.tsx
JIRA Ticket: CALL-3121
We should create engagement using `cti.outgoingCall()` only after inputting a dialNumber.
> Fix createEngagement called twice

- README.md
- demos/demo-react-ts/src/components/screens/KeypadScreen.tsx
- demos/demo-react-ts/test/spec/components/screens/KeypadScreen-test.tsx
Jira Ticket: CALL-3441
| Adds Documentation?      | :white_check_mark:
| Backwards Compatible?          | :white_check_mark:
| Verified that changes work?    | :white_check_mark:
> Send callStartTime in outgoingCall message

- demos/demo-minimal-js/package.json
- demos/demo-minimal-js/webpack.config.js
- demos/demo-react-ts/package.json
- demos/demo-react-ts/webpack.config.js
Jira Ticket: CALL-3266
Serve index.html files from the public directory so that we don't need to build files using the `npm start` command.
| Verified that changes work?    | ✅ 
> Update webpack config and npm scripts

- README.md
- demos/demo-minimal-js/README.md
- demos/demo-react-ts/README.md
Jira Ticket: CALL-3467
- Brief overview of each app "purpose", include some code references
- Add "run in portal" section to both demos
- Add section about running without installation
- Add missing SDK events: onReady, error, resize
- Add disclaimer about the fact we are using mock data and there is no real auth done by the demos
| Adds Documentation?      |:white_check_mark:
| Backwards …
> Finalize new demo app documentation

- demos/demo-minimal-js/package-lock.json
- demos/demo-minimal-js/package.json
- demos/demo-react-ts/package-lock.json
- demos/demo-react-ts/package.json
- demos/demo-react-ts/src/components/screens/DialingScreen.tsx
- package-lock.json
- package.json
Jira Ticket: CALL-3789
Remove handleNextScreen from the useEffect array so that the in-call buttons show up after 2500 ms.
> Temporary fix for handleNextScreen rendering

- demos/demo-minimal-js/index.html
- demos/demo-minimal-js/index.js
Jira Ticket: CALL-3764
Starts an incoming call in `x` seconds in the UI.
Enable call buttons only after incoming or outgoing call has started.
> Start incoming call asynchronously

- demos/demo-minimal-js/index.html
- demos/demo-minimal-js/index.js
Jira Ticket: CALL-3809
Show initialized UI changes when `ready` event is received by disabling and enabling buttons.
> Initialize demo widget when ready event is received from HubSpot

- src/Constants.js
Fix #159
Stop using `require` and use import
| Patch: Bug Fix?          | :white_check_mark:
> Stop using `require` and use import

- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
Set incoming number and incoming contact name in local storage so that they can reinitialized on redirect. This is just for demo app.
Jira Ticket: [CALL-5390](https://issues.hubspotcentral.com/browse/CALL-5390)
> React Demo App: Set incoming number and contact name in localstorage 

- package-lock.json
- package.json
- src/CallingExtensions.js
- test/spec/CallingExtensions-test.js
Pass iFrameOptions to IFrameManager inside CallingExtensions constructor
Jira Ticket: [CALL-5597](https://issues.hubspotcentral.com/browse/CALL-5597)
The PR is fixing the gap between CallingExtensions and IframeManager by passing iFrameOptions from CallingExtensions to IFrameManager.
| Patch: Bug Fix?         | :white_check_mark:
| Automated test …
> Pass iFrameOptions to IFrameManager inside CallingExtensions constructor

- demos/demo-minimal-js/index.js
- src/Constants.js
> Add error to message types

- demos/demo-minimal-js/index.js
- demos/demo-react-ts/src/hooks/useCti.ts
- package-lock.json
- package.json
- src/IFrameManager.js
Jira Ticket: CALL-6290
- Adds the `portalId` and `userId` to the `onReady` payload.
- Adds the `portalId` and `userId`  to the `demo-minimal-js`.
- I attempted to add the `portalId` and `userId`  to the `demo-react-ts` but there's no usages for it right now.
| Minor: New Feature?      |:white_check_mark:
| Automated test …
> Include portalId and userId in the onReady payload

- demos/demo-react-ts/src/hooks/useCti.ts
Jira Ticket: CALL-6290
This fixes changes in https://github.com/HubSpot/calling-extensions-sdk/pull/193 that broke the React Demo widget.
> Fix onReady event in the demo react widget

- demos/demo-minimal-js/index.js
- demos/demo-react-ts/src/components/screens/KeypadScreen.tsx
- demos/demo-react-ts/test/spec/components/screens/KeypadScreen-test.tsx
Jira Ticket: CALL-6250
Send `toNumber` instead `phoneNumber` in outgoingCall payload.
> Send toNumber in outgoing calls

- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx
- demos/demo-react-ts/src/components/screens/IncomingScreen.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
- demos/demo-react-ts/src/types/ScreenTypes.ts
- demos/demo-react-ts/test/spec/components/screens/CallEndedScreen-test.tsx
- demos/demo-react-ts/test/spec/components/screens/IncomingScreen-test.tsx
Jira Ticket: CALL-6484
Update the callStatus to canceled in the React demo widget when we cancel an incoming call instead of answering it.
> Update the callStatus to canceled when we end an incoming call

- demos/demo-minimal-js/index.js
- demos/demo-react-ts/src/hooks/useCti.ts
- package-lock.json
- package.json
- src/CallingExtensions.js
- src/IFrameManager.js
Jira Ticket: CALL-6409
Send ownerId in onReady event for Zoom.
| Patch: Bug Fix?          | 
| Minor: New Feature?      | yes
> Send ownerId in onReady event

- demos/demo-minimal-js/index.html
- demos/demo-minimal-js/index.js
Jira Ticket: CALL-6601
Use `state.enforceButtonsOrder` to enforce order of events in the demo minimal js. It is set to false by default. This enables us to test asynchronous SDK events for inbound calling.
> Add toggle to enforce order of events in the demo minimal js

- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/components/screens/CallEndedScreen.tsx
- demos/demo-react-ts/src/components/screens/CallingScreen.tsx
- demos/demo-react-ts/src/types/ScreenTypes.ts
- demos/demo-react-ts/test/spec/components/screens/CallEndedScreen-test.tsx
Jira Ticket: HMR-5511
This PR aims at enabling fake call recording in the demo react app. The user can now click Record button to enable and disable recording and upon saving call, a fake audio url will be saved as hs-call-recording-url in engagement.
| Backwards Compatible?          | ✅ 
| Verified that changes …
> HMR-5511: Enable call recording in react demo app

- demos/demo-minimal-js/index.js
- demos/demo-minimal-js/package-lock.json
- demos/demo-minimal-js/package.json
- demos/demo-react-ts/package-lock.json
- demos/demo-react-ts/package.json
- demos/demo-react-ts/src/hooks/useCti.ts
- index.js
- package-lock.json
- package.json
- src/CallingExtensions.js
- src/Constants.js
- src/IFrameManager.js
- src/typedefs.js
- test/spec/IFrameManager-test.js
- tsconfig.json
- webpack.config.js
Jira Ticket: CALL-6780
This PR aims at adding typedefs for calling-extensions-sdk code along with publishing d.ts files in package so that consumers can use the types for type validation. This also aims at improving code documentation.
| Patch: Bug Fix?          | 
| Minor: New Feature?      | ✅ 
| Expect …
> CALL-6780: Update jsdocs and typedefs to make callId deprecated

- demos/demo-minimal-js/index.js
- demos/demo-minimal-js/package-lock.json
- demos/demo-minimal-js/package.json
- demos/demo-react-ts/package-lock.json
- demos/demo-react-ts/package.json
- demos/demo-react-ts/src/hooks/useCti.ts
- package-lock.json
- package.json
- src/Constants.js
- src/typedefs.js
Related to [732](https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/732)
Informs the calling app when SET_WIDGET_URL failed by introducing the onSetWidgetUrlFailed SDK event.
| Adds Documentation?      |:white_check_mark:
| Rollout/Rollback Plan?         | Standard
| Automated test coverage?       | Internal integration tests
| Verified …
> Introduce onSetWidgetUrlFailed SDK event

- demos/demo-minimal-js/package-lock.json
- demos/demo-minimal-js/package.json
- demos/demo-react-ts/package-lock.json
- demos/demo-react-ts/package.json
- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/components/screens/CallingScreen.tsx
- demos/demo-react-ts/src/components/screens/DialingScreen.tsx
- demos/demo-react-ts/src/components/screens/IncomingScreen.tsx
- demos/demo-react-ts/src/components/screens/KeypadScreen.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
- demos/demo-react-ts/src/types/ScreenTypes.ts
- demos/demo-react-ts/test/spec/components/screens/IncomingScreen-test.tsx
- demos/demo-react-ts/test/spec/components/screens/KeypadScreen-test.tsx
- package-lock.json
- package.json
- src/Constants.js
- src/IFrameManager.js
https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/873
Create a broadcast channel in the demo widget to sync inbound calling across all tabs.
NOTE: This is a proof of concept for implementing cross-tab navigation changes in the demo widget or 3rd party calling app so that the user is able to interact with the call in the HubSpot navigation bar. This should solve for the following goals: 1) Creating a reusable implementation that all 3rd party calling providers can use to sync across open iframes while maintaining the call connection in the popup or calling window, 2) Creating an extensible design that allows us to add or remove new SDK events easily. 
The `iframeLocation` attribute in the SYNC event is currently gated under the `supportsRemote` local storage setting.
~~I have …
> Create a broadcast channel in the demo widget

- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
- demos/demo-react-ts/src/types/ScreenTypes.ts
https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/913
We should sync the remote with any changes initiated from the calling window, such as `LOGGED_OUT` or `LOGGED_IN`.
> Sync the remote with calling window changes

- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
- demos/demo-react-ts/test/spec/components/screens/LoginScreen-test.tsx
https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/913
When receiving a broadcast message in the calling window, we need to invoke the event handler in `_cti` rather than `cti` to send an SDK message to HubSpot. 
This is because the event handler, i.e. cti.initialized(), could technically send a broadcast message to the other tabs if iframeLocation has been set and we don't want to send another broadcast message when receiving one.
| Patch: Bug Fix?          | x
| Q …
> Fix event handlers in broadcast message

- demos/demo-minimal-js/index.js
- demos/demo-react-ts/src/components/App.tsx
- src/IFrameManager.js
https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/736
Set isLoggedIn and isAvailable to true for demo minimal js.
| Patch: Bug Fix?          | x
> Add isAvailable to SDK event

- demos/demo-minimal-js/index.js
- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/components/screens/KeypadScreen.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
- demos/demo-react-ts/src/types/ScreenTypes.ts
- demos/demo-react-ts/test/spec/components/screens/KeypadScreen-test.tsx
https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/973
**Context**
When using demo minimal js, initiate call id fails due to invalid phone number.
When using demo react ts and keypad input field is cleared out, the dial number event does not populate the keypad input field anymore.
**Solution**
For demo minimal js, use valid phone numbers so that initiate call id succeeds.
For demo react ts, update keypad input field with dial number event.
**Dev Notes**
Removed incoming contact match redirect utils.
[BRAVE …
> Fix dial number event in demo widgets

- demos/demo-minimal-js/index.js
- demos/demo-minimal-js/package-lock.json
- demos/demo-minimal-js/package.json
- demos/package-lock.json
- demos/package.json
- package-lock.json
- package.json
- src/IFrameManager.ts
Fix cross tab communication between `github.hubspot.com/calling-extensions-sdk/demo-minimal-js.html` and `app.hubspot.com`.
Send message from Window -> Remote
Receive message in Remote
We see the `INCOMING_CALL` event in multiple tabs but no NAVIGATE_TO_RECORD tabs has opened.
| Automated test …
> Host window in calling-integration-popup-ui to fix cross origin error

- demos/demo-minimal-js/index.js
https://git.hubteam.com/HubSpot/calling-extensions-fe/issues/985
> Trigger events when broadcast message is received

- demos/demo-minimal-js/index.js
- demos/demo-react-ts/src/components/App.tsx
- demos/demo-react-ts/src/components/screens/LoginScreen.tsx
- demos/demo-react-ts/src/hooks/useCti.ts
This updates the demo react widget for usesCallingWindow=false.
If usesCallingWindow is false, we show an open calling window link. The window will allow us to send SDK events to all open tabs.
| Expect Dependencies to …
> Send SDK message to HubSpot if usesCallingWindow=false
